---
abstract: 'Compile .cgi scripts to a code reference like ModPerl::Registry'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
build_requires:
  CGI: '0'
  Capture::Tiny: '0'
  Sub::Identify: '0'
  Switch: '0'
  Test::More: '0'
  Test::NoWarnings: '0'
  Test::Requires: '0'
  Try::Tiny: '0'
configure_requires:
  Module::Build::Tiny: '0.034'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.20, Dist::Zilla version 6.015, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CGI-Compile
no_index:
  directory:
    - eg
    - examples
    - inc
    - share
    - t
    - xt
requires:
  File::pushd: '0'
  Sub::Name: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/miyagawa/CGI-Compile/issues
  homepage: https://github.com/miyagawa/CGI-Compile
  repository: https://github.com/miyagawa/CGI-Compile.git
version: '0.25'
x_contributors:
  - 'Hans Dieter Pearcey <hdp@cpan.org>'
  - 'Jörn Reder <jreder@dimedis.de>'
  - 'kocoureasy <igor.bujna@post.cz>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'Pavel Mateja <pavel@verotel.cz>'
  - 'Rafael Kitover <rkitover@cpan.org>'
  - 'Rafael Kitover <rkitover@gmail.com>'
  - 'Torsten Förtsch <torsten@binary.com>'
x_generated_by_perl: v5.30.3
x_serialization_backend: 'YAML::Tiny version 1.73'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
x_static_install: 1
